application:
  logLevel: debug
  port: 8080
  salt: nwgDRzL2nvVGToPkEEU8Ba582JxSqPyadQSr4UEN
  jwtKey: xsioaiFMrBYjZVEUsMkWkQoCnxUNHmtBiqBZEkPv
  redisUrl: redis://:drowssap123!@redis:6379
  postgresUrl: psql://admin:drowssap123!@postgres:5432/admin
