application:
  logLevel: debug
  port: 8080
  salt: nwgDRzL2nvVGToPkEEU8Ba582JxSqPyadQSr4UEN
  redisUrl: redis://:drowssap123!@127.0.0.1:6379
  postgresUrl: psql://admin:drowssap123!@127.0.0.1:5432/admin
