version: "3.7"
services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    volumes:
      - db-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    volumes:
      - db-redis:/data

  app-install:
    build: .
    container_name: app-install
    command: npm install
    volumes:
      - .:/opt/app

  app-dev:
    build: .
    container_name: app-dev
    command: npm run dev
    restart: always
    volumes:
      - .:/opt/app
    ports:
      - 127.0.0.1:8080:8080

  app-test:
    build: .
    container_name: app-test
    command: npm test
    restart: always
    volumes:
      - .:/opt/app

volumes:
  db-postgres:
  db-redis:
