FROM node:lts-alpine as builder

LABEL maintainer="Flavien PERIER <perier@flavien.io>"
LABEL version="1.0"
LABEL description="NodeJs backend dev"

ARG DOCKER_UID=500
ARG DOCKER_GID=500

WORKDIR /opt/app
COPY . .

RUN apk add --no-cache python3 gcc make
RUN npm install

RUN addgroup -g $DOCKER_GID app && \
    adduser -G app -D -H -h /opt/app -u $DOCKER_UID app && \
    chown -R app:app /opt/app && \
    chmod -R 750 /opt/app

USER app
EXPOSE 8080

CMD npm start
