FROM node:lts-alpine as builder

LABEL maintainer="Flavien PERIER <perier@flavien.io>"
LABEL version="1.0"
LABEL description="NodeJs backend dev"

WORKDIR /opt/app
COPY . .

RUN apk add --no-cache python3 gcc g++ make && \
    rm -Rf node_modules && \
    chmod -R 750 /opt/app && \
    chown -R root:root /opt/app && \
    npm run init

VOLUME /opt/app/src
VOLUME /opt/app/gyp
VOLUME /opt/app/swagger.yaml

EXPOSE 8080
