FROM node:lts-alpine as builder

LABEL maintainer="Flavien PERIER <perier@flavien.io>" \
      version="1.0.0" \
      description="NodeJs backend dev"

WORKDIR /opt/app
VOLUME /opt/app/src
VOLUME /opt/app/gyp
COPY . .

RUN apk add --no-cache python3 gcc g++ make && \
    npm install && \
    npm run build

EXPOSE 8080
